<?php 
$this->form1->setAttribute('class','form-horizontal well');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

foreach($this->form1 as $element) {
	if(!($element instanceof Zend\Form\Element\Submit)) {
	    $element->setAttribute('class', 'form-control');
?>
    <div class="form-group">
	    <?php if($element->getLabel()) { ?>
	    <label class="col-sm-2 control-label" for="<?= $element->getName() ?>"><?= $this->translate($element->getLabel()) ?></label>
	    <?php } ?>
	    <div class="col-sm-10">
            <?= $this->formElement($element) ?>
            <?= $this->formElementErrors($element)?>
             <?php if($element->getName() === 'comments'): ?>
                   <br> <small><span class="badge" id="contact_form_comments_char_count"></span> characters remaining</small>
            <?php endif;?>
	    </div>
	</div>
<?php 	
	}
	else {
        $element->setAttribute('class', 'btn btn-primary');
?>
    <div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">
<?= 
          $this->formelement($element) 
?>
    	</div>
    </div>
<?php 		

	}
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>

<script>
var commentsFld = $('textarea[name=comments]');
var cntBadge = $('#contact_form_comments_char_count');

var maxLength = commentsFld.attr('maxlength');
cntBadge.text(maxLength);
var originalColor = cntBadge.css("background-color");

commentsFld.keyup(function() {
  var length = $(this).val().length;
  var length = maxLength-length;
  var bgColor = originalColor;
  cntBadge.text(length);
  if (length < 51) { bgColor = 'red'; }
  cntBadge.css('background-color', bgColor);
});

//Fire incase we loaded with data
commentsFld.keyup();
</script>