<h1>Admin List Of Contact Us Messages</h1>

<?php 

    $columnsA = ['email', 'name', 'comments', 'time'];
    
    $page = $this->page;
    $orderby = strtolower($this->orderby);
    $order = $this->order;
    
    
?>

<table class="table table-striped">
<thead>
    <tr>
        <?php foreach ($columnsA as $text): ?>
    
        <th nowrap="true"><?= $this->translate(ucfirst($text)) ?> 
        	&nbsp;
        	<a class="list_order" href="<?= $this->url('contactus/list', array('controller'=> 'index', 'action'=>'list', 'page'=> $page, 'orderby' => $text, 'order'=> 'DESC')) ?>">
        		<span class="glyphicon glyphicon-triangle-bottom <?php if (($orderby === $text) && ($order === 'DESC')): ?>ordered_by<?php endif; ?>" title="<?= $this->translate("Order by $text descending") ?>"></span>
        	</a>
        	<a class="list_order" href="<?= $this->url('contactus/list', array('controller'=> 'index', 'action'=>'list', 'page'=> $page, 'orderby' => $text, 'order'=> 'ASC')) ?>">
        		<span class="glyphicon glyphicon-triangle-top <?php if (($orderby === $text) && ($order === 'ASC')): ?>ordered_by<?php endif; ?>" title="<?= $this->translate("Order by $text ascending") ?>"></span>
        	</a>
      	</th>
          	
        <?php endforeach; ?>
        <th></th>
        <th></th>
        <th></th>
    </tr>
</thead>
<tbody>
<?php if (count($this->contactMessages)): ?>
<?php foreach ($this->contactMessages as $message): ?>
   <tr>
            <td nowrap="true"><?= $this->escapehtml($message['email']) ?></td>
            <td nowrap="true"><?= $this->escapehtml($message['fullname']) ?></td>
            <td width="60%"><?= $this->escapehtml($message['comments']) ?></td>
            <td nowrap="true"><?= $this->escapehtml($message['cdate']) ?></td>
            <td><?php
                if($this->user->getId() == $message['id'] || $this->acl->isAllowed($this->user->getRole(),'index','view')) :
            ?>
            <a class="btn btn-sm btn-info" href="<?= $this->url('contactus/default', array('controller'=> 'index', 'action'=>'view', 'id'=> $message['id'])) ?>"><?= $this->translate('View') ?></a>
            <?php
                endif;
            ?>
            </td>
            <td><?php
                if($this->user->getId() == $message['id'] || $this->acl->isAllowed($this->user->getRole(),'index','edit')) :
            ?>
            <a class="btn btn-sm btn-primary" href="<?= $this->url('contactus/default', array('controller'=> 'index', 'action'=>'edit', 'id'=> $message['id'])) ?>"><?= $this->translate('Edit') ?></a>
            <?php
                endif;
            ?>
            </td>
            <td><?php
                if($this->acl->isAllowed($this->user->getRole(),'index','delete')) :
            ?>
            <a class="btn btn-sm btn-danger" href="<?= $this->url('contactus/default', array('controller'=> 'index', 'action'=>'delete', 'id'=> $message['id'])) ?>"><?= $this->translate('Delete') ?></a>
            <?php
                endif;
            ?>
            </td>
    </tr>
<?php endforeach; ?>
<?php else: ?>
	<tr>
		<td colspan="6">
			No records at this time...
		</td>
<?php endif; ?>
</tbody>
</table>
<?php echo $this->paginationControl($this->contactMessages,
                                    'Sliding',
                                    'paginator/sliding',
                                    array('route' => 'contactus/list')
                                    );
