<h1>Admin List Of Contact Us Messages</h1>

<?php if (count($this->contactMessages)): ?>

<table class="table table-striped">
<thead>
    <tr>
        <th><?= $this->translate('Email') ?></th>
        <th><?= $this->translate('Name') ?></th>
        <th><?= $this->translate('Comments') ?></th>
        <th><?= $this->translate('Time') ?></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
</thead>
<tbody>
<?php foreach ($this->contactMessages as $message): ?>
   <tr>
            <td nowrap="true"><?= $this->escapehtml($message['email']) ?></td>
            <td nowrap="true"><?= $this->escapehtml($message['fullname']) ?></td>
            <td><?= $this->escapehtml($message['comments']) ?></td>
            <td nowrap="true"><?= $this->escapehtml($message['cdate']) ?></td>
            <td><?php
                if($this->user->getId() == $message['id'] || $this->acl->isAllowed($this->user->getRole(),'index','view')) :
            ?>
            <a class="btn btn-sm btn-info" href="<?= $this->url('contactus/default', array('controller'=> 'index', 'action'=>'view', 'id'=> $message['id'])) ?>"><?= $this->translate('View') ?></a>
            <?php
                endif;
            ?>
            </td>
            <td><?php
                if($this->user->getId() == $message['id'] || $this->acl->isAllowed($this->user->getRole(),'index','edit')) :
            ?>
            <a class="btn btn-sm btn-primary" href="<?= $this->url('contactus/default', array('controller'=> 'index', 'action'=>'edit', 'id'=> $message['id'])) ?>"><?= $this->translate('Edit') ?></a>
            <?php
                endif;
            ?>
            </td>
            <td><?php
                if($this->acl->isAllowed($this->user->getRole(),'index','delete')) :
            ?>
            <a class="btn btn-sm btn-danger" href="<?= $this->url('contactus/default', array('controller'=> 'index', 'action'=>'delete', 'id'=> $message['id'])) ?>"><?= $this->translate('Delete') ?></a>
            <?php
                endif;
            ?>
            </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php endif; ?>

<?php echo $this->paginationControl($this->contactMessages,
                                    'Sliding',
                                    'paginator/sliding',
                                    array('route' => 'contactus/list')
                                    );
