
<div class="container-fluid">
 <div class="row">
   <div class="col-sm-12">
    <h1>
    <?php echo sprintf($this->translate('Contact Us Comments Detail View')); ?>
    </h1>
   </div>
  </div>
 <div class="row well">
  <div class="col-sm-12">
    <h4><?php echo sprintf($this->translate('Id: %s'), $this->commentToView->getId()) ?></h4>
    <h4><?php echo sprintf($this->translate('Emal: %s'), $this->commentToView->getEmail()) ?></h4>
    <h4><?php echo sprintf($this->translate('Name: %s'), $this->commentToView->getFullname()) ?></h4>
    <h4><?php echo sprintf($this->translate('Time: %s'), $this->commentToView->getCdate()->format('Y-m-d H:i:s')) ?></h4>
    <h4><?php echo sprintf($this->translate('Comments: %s'), $this->commentToView->getComments()) ?></h4>
   </div>
 </div>
 <div class="row">
  <div class="col-sm-12">
   <a class="btn btn-lg btn-primary" href="<?= $this->url('contactus/default', array('controller'=> 'index', 'action'=>'edit', 'id'=> $this->commentToView->getId())) ?>"><?= $this->translate('Edit') ?></a>

   <a class="btn btn-lg btn-danger" href="<?= $this->url('contactus/default', array('controller'=> 'index', 'action'=>'delete', 'id'=> $this->commentToView->getId())) ?>"><?= $this->translate('Delete') ?></a>
  </div>
 </div>
</div>




