<h1>
<?php echo sprintf($this->translate('Hello: %s'), $user->getName()) ?>
</h1>

<h2><?php echo sprintf($this->translate('Id: %s'), $user->getId()) ?></h2>
<h2><?php echo sprintf($this->translate('Emal: %s'), $user->getEmail()) ?></h2>
<h2><?php echo sprintf($this->translate('Name: %s'), $user->getName()) ?></h2>
<h2><?php echo sprintf($this->translate('Role: %s'), $user->getRole()) ?></h2>
<h2><?php echo sprintf($this->translate('Phone: %s'), $user->getPhone()) ?></h2>




