<form method="post" class="form-horizontal well">
<fieldset>
  <div class="form-group">
    <label for="inputEmail" class="col-sm-2 control-label"><?= $this->translate('Email') ?></label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="username" name="username" placeholder="Email" required="required">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword" class="col-sm-2 control-label"><?= $this->translate('Password') ?></label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="password" name="password" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default"><?= $this->translate('Log in') ?></button>
    </div>
  </div>
  </fieldset>
</form>
