<?php 
    echo $this->doctype(); 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('PHPtc'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))               
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    	<span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" id="navbar-brand-1" href="<?php echo $this->url('home') ?>">PHPtc</a>
                 </div>
                     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    	<ul class="nav navbar-nav">
<?php 
        $navHelper = $this->navigation('navigation');
        $containers = $navHelper->getContainer(); 
        
        foreach($containers->getPages() as $page) {
            $class = "";
            if ($page->isActive()) {
                $class = "active";
                
                /* Only works for User section
                $currentPageLabel  = $page->getLabel();
                $currentPageLabel  = $this->translate($currentPageLabel); // translated label
                $currentPageLabel  = $this->escapehtml($currentPageLabel); // sanitized label
                */
            } 
                                    
            if(count($page)) {
                 // if there are subpages we render the menu a bit different
                 $label  = $page->getLabel();
                 $label  = $this->translate($label); // translated label
                 $label  = $this->escapehtml($label); // sanitized label
                 printf('<li class="dropdown%s">'."\n",
                         ($class?' '.$class:'')
                 );
                 printf('    <a href="%s" class="dropdown-toggle" data-toggle="dropdown" role="button">%s<b class="caret"></b></a>'."\n",
                             $page->getHref(), 
                             $label
                 );
                 echo '<ul class="dropdown-menu">'."\n";
                 foreach($page as $subPage) {
                       if(!$navHelper->accept($subPage)) {
                       	continue;
                       }
                       printf("<li>%s</li>\n",$navHelper->htmlify($subPage));
                                        }
                       echo "</ul></li>\n";
                  }
                  else {
                       printf("<li class=\"%s\">%s</li>\n",$class,$navHelper->htmlify($page));	
                       }	
                  }
?>						</ul>
					</div><!--/.nav-collapse -->
                </div>
            </div>
            <div class="breadcrumb">
            	<?php 
            	   echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(1)->setseparator(' >>'.PHP_EOL);
            	?>
            </div>    
<?php 
$namespaces = array ('error','success','info','default');
foreach ($namespaces as $namespace) {
	$flashMessages = $this->flashmessenger()->render($namespace);
    if (!empty($flashMessages)) {
?>
<div id="myAlert" class="alert alert-<?= $namespace ?>" data-alert="alert">
    <a class="close" data-dismiss="alert">×</a>
    <?= $this->translate($flashMessages )?>
</div>
<?php 	
	}
}    
?>  
        <div class="container">
        	<?php if(isset($currentPageLabel)){ printf("<div class=\"page-header\"><h1>%s</h1></div>", $currentPageLabel); /*alway null currently*/} ?>
            <?php echo $this->content; ?>
        </div>
        <hr>
        <footer>
        	<div class="container">
            	<div class="row">
                    <div class="col-md-4">
                    	<p>&copy; <?php if(date('Y')==2016){ echo '2016'; } else { echo '2016 - '.date('Y');} ?> by PHPtc.com. <?php echo $this->translate('All rights reserved.'); ?></p>
                    </div>
                   	<div class="col-md-offset-4 col-md-4">
                    	<a href="<?php printf("%s", '/application/index/privacy'); ?>"><?php echo $this->translate('Privacy'); ?></a>
                    </div>
                </div>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
