<?= $this->doctype(); ?>

<html lang="en">

	<?= $this->partial("application/index/partials/head") ?>
    
    <body class="phptc-content">    
    	
    	<?= $this->partial("application/index/partials/navTop") ?>
    	
    	<?= $this->partial("application/index/partials/breadcrumb") ?>
    	
    	<?= $this->partial("application/index/partials/flashMessages") ?>
    	    
    	
        <div class="container"><!-- Content container start -->
        
        	<?= $this->partial("partials/pageHeader") ?>
        
        	<?= $this->content ?>
        	
        </div><!-- Content container end -->
        
        <?= $this->partial("application/index/partials/footer") ?>
    </body>
</html>
