<?= $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php 
            echo $this->headTitle($this->translate('PHPtc'))->setSeparator(' - ')->setAutoEscape(false);

            echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))               
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css');

            echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js'); 
        ?>

    </head>
    <body>    
    	<div class="navbar-wrapper">
    		<div class="container">
    			<nav class="navbar navbar-fixed-top navbar-inverse ">
          			<div class="container">
            	 		<div class="navbar-header">
                      		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand brand" title="<?= $this->translate('Link to home page') ?>" href="<?= $this->url('home') ?>">PHPtc</a>    
                        </div>
                        <div class="navbar-collapse collapse" id="navbar">
                            <ul class="nav navbar-nav">
                            	<?php 
                                    $navHelper = $this->navigation('navigation');
                                    $containers = $navHelper->getContainer(); 
                                    
                                    foreach ($containers->getPages() as $page) {
                                        $class = "";
                                        
                                        if (count($page)) {
                                                                                       
                                            // Render subpages
                                            $title  = $page->getTitle();
                                            $title  = $this->translate($title);
                                            $title  = $this->escapehtml($title);
                                            $label  = $page->getLabel();
                                            $label  = $this->translate($label);
                                            $label  = $this->escapehtml($label);
                                            
                                            if ($page->isActive()) {
                                             $class = "active";
                                             $currentpageTitle = $title;
                                            }
                                            
                                            $subPages = '';
                                            foreach ($page as $subPage) {
                                                if(!$navHelper->accept($subPage)) {
                                                    continue;
                                                }
                                                $subPages .= sprintf("<li>%s</li>\n",$navHelper->htmlify($subPage));
                                                 
                                                 
                                                if ($subPage->isActive()) {
                                                    $class = "active";
                                                    $currentpageTitle  = $subPage->getTitle();
                                                    $currentpageTitle  = $this->translate($currentpageTitle);
                                                    $currentpageTitle  = $this->escapehtml($currentpageTitle);
                                                     
                                                }
                                            }
                                            
                                            printf('<li class="dropdown%s">'."\n",($class?' '.$class:''));
                                            
                                            printf('    <a href="%s" class="dropdown-toggle" data-toggle="dropdown" role="button" title="%s, click to open menu">%s<b class="caret" title="'.$this->translate('Click to open menu').'"></b></a>'."\n",
                                                     $page->getHref(), 
                                                     $title,
                                                     $label
                                            );
                                            echo '<ul class="dropdown-menu">'."\n";
                                            
                                            echo $subPages;
                                            
                                            echo "</ul></li>\n";
                                         } else {
                                            printf("<li class=\"%s\">%s</li>\n",$class,$navHelper->htmlify($page));	
                                         }	
                                    }
                                ?>
                            </ul>
                        </div><!--/.nav-collapse end -->
            		</div>
        		</nav>   
        	</div>
        </div>         
    	<?php 
        	$serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
        	$routeMatch = $serviceLocator->get('Application')->getMvcEvent()->getRouteMatch();        	
            	
            if ($routeMatch->getMatchedRouteName() !== 'home'){
                echo '<div class="container breadcrumb">';
                 
                $homeLink = '';
                if ($routeMatch->getMatchedRouteName() !== 'application/default') {
                    $homeLink = '<a href="/" title="'.$this->translate('Link to home page').'">Home</a> >> ';
                }
                
                echo $homeLink.$this->navigation('navigation')->breadcrumbs()->setMinDepth(1)->setseparator(' >> ');
                echo '</div>';
            } else {
                echo '<br>';
            }
    
            $namespaces = array ('error','success','info','default','warning');
            
            foreach ($namespaces as $namespace) {
            	$flashMessages = $this->flashmessenger()->render($namespace);
                if (!empty($flashMessages)) {
        ?>
                <div class="container">
                    <div class="alert alert-<?= str_replace('error', 'danger', $namespace) ?>" data-alert="alert">
                        <a class="close" data-dismiss="alert">×</a>
                        <?= '<strong>'.ucfirst($namespace)."!</strong> ".$this->translate($flashMessages )?>
                    </div>
                </div>
        <?php 	
                }
            }    
        ?>  
        <div class="container">
        	<?php 
                if (isset($currentpageTitle)) { 
                   printf("<div class=\"page-header\"><h2>%s</h2></div>", $currentpageTitle);
                }
                echo $this->content; 
            ?>
        </div>
        <hr>
        <footer class="container">
            	<div class="row">
                    <div class="col-md-4">
                    	<p>&copy; <?= (date('Y')==2016)? '2016': '2016 - '.date('Y'); ?> by PHPtc.com. <?= $this->translate('All rights reserved.'); ?></p>
                    </div>
                   	<div class="col-md-offset-4 col-md-4">
                    	<a href="<?= printf("%s", '/application/index/privacy'); ?>"><?= $this->translate('Privacy'); ?></a>
                    </div>
                </div>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
