<h1><?= $this->translate($this->pageTitle)?></h1>

<?php 

    $columnsA       = $this->columns;
    $listActionsA   = $this->listActions;
    $page           = $this->page;
    $orderby        = strtolower($this->orderby);
    $order          = $this->order;
    $routeBase      = $this->route;
    $controller     = $this->controller;
    
?>

<table class="table table-striped">
<thead>
    <tr>
        <?php foreach ($columnsA as $columnKey=>$column): 
                $text = $column['text'];
        ?>
            <th<?php foreach ($column['attributes'] as $k=>$v){ echo " $k='$v'"; } ?>><?= $this->translate(ucfirst($text)) ?> 
            	&nbsp;
            	<a class="list_order" href="<?= $this->url($routeBase.'/list', array('controller'=> $controller, 'action'=>'list', 'page'=> $page, 'orderby' => $columnKey, 'order'=> 'DESC')) ?>">
            		<span class="glyphicon glyphicon-triangle-bottom <?php if (($orderby === $columnKey) && ($order === 'DESC')): ?>ordered_by<?php endif; ?>" title="<?= $this->translate("Order by $text descending") ?>"></span>
            	</a>
            	<a class="list_order" href="<?= $this->url($routeBase.'/list', array('controller'=> $controller, 'action'=>'list', 'page'=> $page, 'orderby' => $columnKey, 'order'=> 'ASC')) ?>">
            		<span class="glyphicon glyphicon-triangle-top <?php if (($orderby === $columnKey) && ($order === 'ASC')): ?>ordered_by<?php endif; ?>" title="<?= $this->translate("Order by $text ascending") ?>"></span>
            	</a>
          	</th>          	
        <?php endforeach; ?>
        <th width="6%">&nbsp;</th>
        <th width="6%">&nbsp;</th>
        <th width="7%">&nbsp;</th>
    </tr>
</thead>
<tbody>
<?php if (count($this->entities)): ?>
<?php foreach ($this->entities as $entity): ?>
   <tr>
        <?php foreach ($columnsA as $k=>$column): ?>
            <td><?= $this->escapehtml($entity[$k]) ?></td>
        <?php endforeach; ?>
        
        <?php foreach ($listActionsA as $actionKey=>$action): 
                $actionText = $action['text'];
        ?>
            <td><?php
            if($this->acl->isAllowed($this->user->getRole(),$controller, $actionText)) :
            ?>
            <a class="<?php echo $this->escapehtml($action['styleClass']); ?>" href="<?= $this->url($routeBase.'/default', array('controller'=> $controller, 'action'=>$actionKey, 'id'=> $entity['id'])) ?>"><?= $this->translate(ucfirst($actionText)) ?></a>
            <?php
                endif;
            ?>
        <?php endforeach; ?>
    </tr>
<?php endforeach; ?>
<?php else: ?>
	<tr>
		<td colspan="<?php echo (count($columnsA) + 3)?>">
			No records at this time...
		</td>
<?php endif; ?>
</tbody>
</table>
<?php echo $this->paginationControl($this->entities,
                                    'Sliding',
                                    'paginator/sliding',
                                    array('route' => $routeBase.'/list')
                                    );
