<?php 

    $columnsA       = $this->columns;
    $listActionsA   = $this->listActions;
    $page           = $this->page;
    $orderby        = strtolower($this->orderby);
    $order          = $this->order;
    $routeBase      = $this->route;
    $controller     = $this->controller;
    
?>

<table class="table table-striped">
<thead>
    <tr>
        <?php foreach ($columnsA as $columnKey=>$column): 
                $text = $column['th_text'];
        ?>
            <th<?php if (isset($column['th_attributes'])) {foreach ($column['th_attributes'] as $k=>$v){ echo " $k='$v'"; }} ?>><?= $this->translate(ucfirst($text)) ?> 
            	&nbsp;
            	<a class="list_order" href="<?= $this->url($routeBase.'/list', array('controller'=> $controller, 'action'=>'list', 'page'=> $page, 'orderby' => $columnKey, 'order'=> 'desc')) ?>">
            		<span class="glyphicon glyphicon-triangle-bottom <?php if (($orderby === $columnKey) && ($order === 'desc')): ?>ordered_by<?php endif; ?>" title="<?= $this->translate("Order by $text descending") ?>"></span>
            	</a>
            	<a class="list_order" href="<?= $this->url($routeBase.'/list', array('controller'=> $controller, 'action'=>'list', 'page'=> $page, 'orderby' => $columnKey, 'order'=> 'asc')) ?>">
            		<span class="glyphicon glyphicon-triangle-top <?php if (($orderby === $columnKey) && ($order === 'asc')): ?>ordered_by<?php endif; ?>" title="<?= $this->translate("Order by $text ascending") ?>"></span>
            	</a>
          	</th>          	
        <?php endforeach; ?>
        
        <?php foreach ($listActionsA as $actionKey=>$action): ?>
            <th width="6%">&nbsp;</th>
        <?php endforeach; ?>
    </tr>
</thead>
<tbody>
<?php if (count($this->entities)): ?>
<?php foreach ($this->entities as $entity): ?>
   <tr>
        <?php foreach ($columnsA as $k=>$column): 
                       
               $format = $column['td_formats']['tcDefaultCellFormat'];
               if (isset($column['td_formats'][$entity[$k]])) {
                   $format = $column['td_formats'][$entity[$k]];
               }
               
               $text = sprintf($format, $entity[$k]);
        ?>
            <td<?php if (isset($column['td_attributes'])) {foreach ($column['td_attributes'] as $k=>$v){ echo " $k='$v'"; }} ?>><?= $this->translate($text) ?></td>
        <?php endforeach; ?>
        
        <?php foreach ($listActionsA as $actionKey=>$action): 
                $actionText = $action['text'];
        ?>
            <td><?php
            if($this->acl->isAllowed($this->user->getRole(),$controller, $actionText)) :
            ?>
            <a class="<?php echo $this->escapehtml($action['styleClass']); ?>" href="<?= $this->url($routeBase.'/default', array('controller'=> $controller, 'action'=>$actionKey, 'id'=> $entity['id'])) ?>"><?= $this->translate(ucfirst($actionText)) ?></a>
            <?php
                endif;
            ?>
        <?php endforeach; ?>
    </tr>
<?php endforeach; ?>
<?php else: ?>
	<tr>
		<td colspan="<?php echo (count($columnsA) + 3)?>">
			No records at this time...
		</td>
<?php endif; ?>
</tbody>
</table>
<?php echo $this->paginationControl($this->entities,
                                    'Sliding',
                                    'paginator/sliding',
                                    array('route' => $routeBase.'/list')
                                    );
