<?php 

$serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
$routeMatch = $serviceLocator->get('Application')->getMvcEvent()->getRouteMatch();
 
if ((isset($routeMatch)) && ($routeMatch->getMatchedRouteName() !== 'home')){
    echo '<div class="container breadcrumb">';
     
    $homeLink = '';
    if ($routeMatch->getMatchedRouteName() !== 'application/default') {
        $homeLink = '<a href="/" title="'.$this->translate('Link to home page').'">Home</a> <span>>></span> ';
    }

    echo $homeLink.$this->navigation('navigation')->breadcrumbs()->setMinDepth(1)->setseparator(' <span>>></span> ');
    echo '</div>';
} else {
    echo '<br>';
}

