<footer class="navbar-inverse footer">
	<div class="container">
		<div class="row">
            <div class="col-md-12">
            	&nbsp;
            </div>
        </div>
    	<div class="row">
            <div class="col-md-4">
            	<a href="<?= sprintf("%s", '/application/index/privacy') ?>"><?= $this->translate('Privacy') ?></a>                  	
            </div>
           	<div class="col-md-offset-4 col-md-4 text-muted">
            	&copy; <?= (date('Y')==2016)? '2016': '2016 - '.date('Y') ?> by PHPtc.com.
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
            	&nbsp;
            </div>
        </div>
    </div>
</footer>