<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
	<meta name="author" content="">
    <?php 
                
        echo $this->headTitle($this->translate('PHPtc'))->setSeparator(' - ')->setAutoEscape(false);

        
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))               
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');

        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                  ->prependFile($this->basePath() . '/js/jquery.min.js'); 
    ?>    
</head>