<div class="jumbotron">
    <h2><?php 
        echo sprintf($this->translate('Welcome to %s '), $this->applicationName);
        echo sprintf($this->translate('version: %s'), $this->version) ?>
    </h2>
    <h4>This project is for demonstration and learning for PHP and Zend Framework 2. Based initially on the project in the Learnzf2 book by Slavey Karadzhov</h4>
</div>

<div class="well">
    <h4>demo user: </h4>
    <p>demouser@nathanhaley.com </p>
  	<p> pass123</p>
  	<br>
    <h4>demo admin:</h4>
    <p>demoadmin@nathanhaley.com</p>
    <p>pass123</p>
</div>

<div class="well">

<h4>Site Change log:</h4>

<p>2016-07-08: Created shared list page template including pagination/sort, implemented for user and contact us lists. Bug fix: User list breadcrumb.</p>

<p>2016-07-07: Added order by functionality for admin list page for contact us form submissions.</p>

<p>2016-07-06: Added logging in newly registered users and fix allowing admins to add accounts.</p>

<p>2016-07-05: Adding unit tests for Application Index Controller and User log in.</p>

<p>2016-06-27: Updated to latest Bootstrap css/js. Fix/update nav for current Bootstrap. Login: failure message added, responsive styling started: Contact Us add/edit, User login/add/register/edit. Contextual menu fix;</p>

<p>2016-06-26: Added: Contact Us module with contact form submission, and admin functions for list/edit/delete; breadcrumb; Minor style updates;</p>

<p>2016-06-24: Fixed exam/test scoring, added exam name and user's name to certificate.</p>

<p>2016-06-23: Completed pdf certificate generation and send by email.</p>

<p>2016-06-22: Account menu mods: view/edit/delete only accessible from list page. View page updated with buttons to edit|delete. Some AccountController refactoring for reusable chunks for methods findUserEntity and formAddFields. Button style updates on list pages for users and tests.</p>

<p>2016-06-21: Added debug display switch, initial view and me pages, and initial admin pages for user list, edit, delete</p>

<p>2016-06-20: Completed through the pagination chapter, includes exam, reseting/loading exam from file, exam list page</p>

<p>2016-06-18: Added basic nav, initial ACL, log in/out</p>

<p>2016-06-17: Implemented initial add user account functionality at route: account/add</p>

</div>
